//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Libro.h
//  @ Date : 30/11/2021
//  @ Author : 
//
//


//#if !defined(_LIBRO_H)
//#define _LIBRO_H


class Libro {
public:
	Libro();
	Libro(string tit, string au, int tE, int eP);
	void setTitulo(string tit);
	void setAutor(string au);
	void setTotalEjemplares(int tE);
	void setEjemplaresPrestados(int eP);
	string getTitulo();
	string getAutor();
	int getTotalEjemplares();
	int getEjemplaresPrestados();
	bool prestamo();
	bool devolucion();
	//string toString();
	string toString(string titulo, string autor, int totalEjemplares, int ejemplaresPrestados);
private:
	string titulo;
	string autor;
	int totalEjemplares;
	int ejemplaresPrestados;
};

//#endif  //_LIBRO_H
